fix js errors, error in case of unexpected units
Eliminate illegal js, break keyword is not allowed outside of loops/switches.

Cause process to error out in case of mmol.
Prevent errors like this:

foo$ oref0-get-profile monitor/pump-history.json tagrgets-mm
ol.json

/usr/local/lib/node_modules/openaps-js/bin/oref0-get-profile.js:50
        break;
        ^^^^^
SyntaxError: Illegal break statement
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
bewest@hither:~/Documents/foo$

In favor of errors like this:

o$ oref0-get-profile monitor/pump-history.json tagrgets-mmol.json monitor/insulin-sensitivities.json monitor/active-basal-profile.json monitor/carb-ratios.json max_iob.json
BG Target data is expected to be expressed in mg/dL. Found mmol/L in tagrgets-mmol.json .
bewest@hither:~/Documents/foo$