restore ww pumps for 0.7.0-dev (#1176)
* update example Go versions to verison with token based authentication

* run travis with latest node 8 and node 10 (both LTS)

* remove init pump comms to set ww parameters. this is now done with ecc1 go libraries. this will also remove ti usb reset support

* fix duplicate radio_locale in pump.ini and don't run default code in an else block

* create pump.ini before nightscout autoconfigure-device-crud

* remove ww_ti_usb_reset

* remove extra empty line

* WIP to deprecate old MDT CGM setup (new MDT CGM Go stuff just requires a switch in preferences.json.
WIP to remove use of pump.ini in favor of storing pump serial, radio locale, and tty port in preferences.json.

* remove depreacte medtronic non Go setup

* rename openaps-*.sh to oref0-*.sh and adjust

* remove crypto 0.0.3, it is included in Node

this removes warning: npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

* update npm packages

* use jq >= 1.5 for slurpfile.

jq: Unknown option --slurpfile
Use jq --help for help with command-line options,
or see the jq documentation at http://stedolan.github.com/jq
module.js:675
    throw err;
    ^

SyntaxError: /root/myopenaps/updated_prefs.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:672:27)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/.rootfs/usr/local/lib/node_modules/oref0/bin/oref0-get-profile.js:81:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
Could not run oref0-get-profile

---

# jq --version
jq-1.4-1-e73951f

* Introduce is_debian_jessie function and use it to install jq from jessie-backports if using older debian version (e.g. on jubilinux 0.2.x )

* still add openaps to oref0-packages for now

* remove creation of pump.ini as scott suggests

* revert ac43e91a1a6a25fb3f42c1423ede7254a6e29cea renaming as scott suggests

* switch back to openaps-packages.sh instead of oref0-packages.sh as scott suggests, keep jq fix for debian_jessie

* on a fresh rpi3 there is no /usr/local/bin/mmtune so don't move it

* implement changes as requested by scott

* upgrade yargs to avoid security vulnerability . did a quick check of the major changes and could not find deprecations we use

* pull https://github.com/openaps/oref0/pull/1203 into this branch and resolve merge conflict

* some cleanup, consistent radio_locale string in pump.ini

* there is no need to install the released oref0 globally, because oref0-setup.sh will install it when it's run

* prevent spurious grep message if monitor/mmtune.json is empty

```
# oref0-mmtune
mmtune: WW
2019/02/17 23:04:04 cannot connect to CC111x radio on /dev/spidev5.1
2019/02/17 23:04:04 cc111x: no response
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
```

* 1) cleanup ugly pump.ini stuff for edison. 2) mmeowlink is not only needed for mdt CGM, try to see if we can get mmeowlink back to work if users specifies port with mmeowlink in it 3) add todo's

* add missing then

* fix package.json typo and upgrade coveralls to 3.0.3

* remove webpack from this branch

* upgrade share2nightscout bridge and yargs